### ISSUE TITLE
Not installable

### ISSUE THREAD

**Issue by sudoforge** [aidistan/atom-symbols-view-plus#1]
Browsing through symbol plugins, attempted to install yours, received an error:

``` bash
$ apm install symbols-view-plus
Unable to download https://www.atom.io/api/packages/symbols-view-plus/versions/0.113.0-plus.3/tarball: 400 Bad Request Repository inaccessible
```

**Comment by aidistan** [comment]
Hi @bddenhartog, thanks for the interest.

This package is indeed unable to install and needs to be republished. I created atom/apm#575 a month ago but recieved no reply.

You could try to install the package manually or just wait the issue to be fixed.

**Comment by aidistan** [comment]
We still get no response from atom/apm#575.

For anyone who is interested in this packages, please use `apm install aidistan/atom-symbols-view-plus` instead.

**Comment by sudoforge** [comment]
@aidistan Given that you seem to have re-uploaded it to atom's repositories, I think I'll go ahead and close this.

**Comment by aidistan** [comment]
@bddenhartog atom/apm#575 was just fixed. `apm install atom-symbols-view-plus` should work fine now.
