### ISSUE TITLE
Can't start symbol-view-plus

### ISSUE THREAD

**Issue by ocoka** [aidistan/atom-symbols-view-plus#12]
[X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
After install the symbol-view-plus I've restart the Atom and got in console :
> Failed to require the main module of 'symbols-view-plus' because it requires one or more incompatible > native modules (build).
> Run `apm rebuild` in the package directory and restart Atom to resolve

### Atom version
`1.17.2 x64
`Ubuntu 16.04

**Comment by aidistan** [comment]
Hi @ocoka. The package needs python and other compilers to build some native modules. It seems that the installation was failed when trying to do that.

I suggest you to
1. check your python interpreter and other compilers (see the instruction [here](https://github.com/aidistan/atom-symbols-view-plus/wiki/FAQ:-unable-to-install-on-Windows,-Linux-or-MacOS))
2. reinstall the package or just rebuild it

**Comment by ocoka** [comment]
`ocoka@work:~/.atom$ apm -v`
> apm  1.17.0
> npm  3.10.5
> node 6.9.5 x64
> python 2.7.12
> git 2.7.4

I've tried to `apm rebuild` in `~/.atom/packages/symbols-view-plus/` directory
> Rebuilding modules ✓

No luck !

Also i've tried to clean `node_modules` and `apm i`, all modules was installed succesfully, but I still get that error in `Atom`.

I saw that the `ctags` module need to have native libs, but it was  rebuilt succesfull (I've cleaned `~/.atom/packages/symbols-view-plus/node_modules/ctags/build/Release` , and made `apm rebuild`, and that directory fills with `ctags.node` etc...)

So, have you any further suggestions ?

**Comment by ocoka** [comment]
~As I see in the code you use `async` but does `node 6.9.5` that cames with `atom 1.17.2` support this ?~
Ah, I understand, Atom uses `babel` under the hood ))

**Comment by aidistan** [comment]
@ocoka I've tried the installation on a virtual machine running Ubuntu 16.04. Everything just works fine. Sorry, but I've no idea how to solve this. :sob:

**Comment by ocoka** [comment]
Yep, I also have made my system clean from any presence of `electron` and `atom` and reinstall it from **atom.io** (befor that it was installed from *webupd team*), and with no other packages installed, I do clean install of `symbols-view-plus` package, and result the *same*.... but... ))

To be honestly, I don't know what moment it was fixed, but without any other package installed, and after I remove manually a subdirectory `~/.atom/packages/symbols-view-plus/node_modules/ctags`, and install it with **npm** (a system one, by the way, I have a **node 7** installed locally), and restart **Atom**, i got a different problem, it was about _"..some version difference from what was expected "_, and after it, I go to the package directory, and I've made `apm rebuild` (i do that many times before), but in this case, the package loaded, and all works fine ! 

*I don't know what that was*
