### ISSUE TITLE
Warning detected during the generation ctags-linux: ".tags" doesn't look like a tag file; I refuse to overwrite it.

### ISSUE THREAD

**Issue by marcelhekking** [aidistan/atom-symbols-view-plus#13]
### Prerequisites

-->

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Since last update of 'atom-symbols-view-plus', I get a warning that Atom can't write to the  .tags file,

### Steps to Reproduce

1. Open a Python file
2. Close that file
3. Warning appears

**Expected behavior:** No warning

**Actual behavior:** Warning

**Reproduces how often:** always

### Versions
Atom version 1.17.2
atom-symbols-view-plus version: 0.116.1-plus.3
Linux 17.04

**Comment by aidistan** [comment]
@marcelhekking It may be caused by the upgraded ctags or an accident overwrite of the tag file. Have you tried to delete the old .tags file?

**Comment by marcelhekking** [comment]
I just deleted  my .tag file and let atom-symbols-view-plus generate a new one but no success. I still get the warning.

**Comment by aidistan** [comment]
@marcelhekking I guess this situation was caused by some dotfiles. See yongkangchen/atom-ctags#19, find the one that impedes CTAGS, and remove it temporarily.

**Comment by marcelhekking** [comment]
I found out that generating symbols with atom-symbols-view-plus works. Also looking up symbols works fine. However, although everything works but it keeps generating these warnings.

**Comment by aidistan** [comment]
I see. I have published a new version which should suppress these harmless warnings.

**Comment by marcelhekking** [comment]
Thank you for your effort but I'm afraid this update made it worse. It is not a warning anymore but an error :
```
Error detected during the generation
ctags-linux: ".tags" doesn't look like a tag file; I refuse to overwrite it.
```

**Comment by marcelhekking** [comment]
No sorry. It works! I removed the old .tags file and now there is no error anymore! Thanx!!
