### ISSUE TITLE
Nesting options?

### ISSUE THREAD

**Issue by onetrev** [aidistan/atom-symbols-view-plus#16]
Just wondering if it's on the roadmap to have some nesting options? For example, if I have some functions with a bunch of variables the list of symbols gets really long and it's harder to spot the more important parts -- the functions. It would be great to have both the option to close/expand a single function in your list, as well as set a global option for expanded/closed by default on load.

Love what you've created here either way! Thank you!!

**Comment by aidistan** [comment]
It is possible to implement this feature if we switch the old ctags to `universal-ctags`.

Yes, it's on the roadmap. But I'm still thinking whether to implement it here, or in a seperate package.

**Comment by aidistan** [comment]
I have decided to implement this feature **in a separate package**, and keep this package as a slight improvement of the official `symbols-view`.

But I'm so busy these days that I could not give a launch day for that new package. Sorry for that.
