### ISSUE TITLE
Autocomplete content issues

### ISSUE THREAD

**Issue by onetrev** [aidistan/atom-symbols-view-plus#17]
Sorry, I'm not sure how to title or describe this. But below is an example that hopefully explains it. This is in my .tags file, pulled from my Sass variables file.

`max-width	C:\websites\infinite\wp-content\themes\infini\assets\scss\utils\_variables.scss	/^$max-width: 1170px;$/;"	function`

So the problem is it should just autocomplete as just `$max-width`, because obviously the variable value is not needed and has to be deleted. This is the problem for all my variables in my Sass file. Any thoughts? Thanks!

**Comment by aidistan** [comment]
Hi @onetrev, thanks for trying this package. Actually, the variable value you concerned here is not related to autocompletions. It's just a part of a regexp to find the line where `max-width` is defined. When trying to auto complete, only `max-width` will be suggested.

**Comment by onetrev** [comment]
Thank you for making the package! To clarify though my issues was I would type "$max-wid" let's say, and autocomplete would pop up as expected, but when I'd select the $max-width var that I wanted, what would go on the page would be that whole bit: `$max-width: 1170px;`

**Comment by aidistan** [comment]
@onetrev OK I got u. Try the new version which has solved this issue please.

**Comment by onetrev** [comment]
Awesome, thanks for that fix!

**Comment by onetrev** [comment]
Hmm, there may be a problem still. I finally had some time to test this fully, and I just noticed that autocomplete now no longer contains any of the Sass variables generated in the tags file. The original issue was extra info showing up, now we have nothing. Let me know if you need more info!

**Comment by onetrev** [comment]
Never mind, seems like a restart of Atom and now autocomplete of variables from .tags is working again. 

However there is one small issue still remaining regarding autocomplete content. For CSS classes (and I'd assume IDs) the `.` and `#` are being included in the autocomplete.

Ex:
`<div class=".TestClass"></div>`

The `.` should not be there, just the class name. Otherwise it's awesome this works across your project, something Atom has been lacking for years!

**Comment by aidistan** [comment]
Hi @onetrev . Although it looks like a small issue at the beginning, there is no elegant way to fix this in all situations. For your specific case, I have pushed [a commit](https://github.com/aidistan/atom-symbols-view-plus/commit/b2ac22b31d07faa31ea63b30b5b051ab4591c201) for you, try to hack the package with it~

Note: this commit only suits your situation, thus I won't push it to the master branch.
