### ISSUE TITLE
Toggling dock does not toggle (toggles on, not off)

### ISSUE THREAD

**Issue by onetrev** [aidistan/atom-symbols-view-plus#18]
A minor issue, but I've noticed toggling file symbols (or project symbols) does not actually toggle properly. It looks like the command or keystroke will toggle it on, but the same command/keystroke again does nothing, when it should toggle off right?

_note:_ slightly off topic, but I noticed docs / settings page for keybindings doesn't show `ctrl+shift+r` for toggling project symbols.

**Comment by aidistan** [comment]
Yes, it's a known issue. Since there is no "toggle off" for dock items, I just give up it :laughing: 

The official tree view (`ctrl + \`) seems to provide a "toggle off", but it will hide any dock items in the same dock!

**Comment by onetrev** [comment]
Gotcha. Never noticed that. I have a couple of packages that use docks, and they too just toggle off entirely. Not ideal for sure! Personally I prefer that to it doing nothing, but no worries. Thanks for the follow up.
