### ISSUE TITLE
Feature Request: Docks Support

### ISSUE THREAD

**Issue by DamnedScholar** [aidistan/atom-symbols-view-plus#9]
Is there planned support for the recent docks feature?

**Comment by aidistan** [comment]
@DamnedScholar Yeah, [this new feature](http://blog.atom.io/2017/05/23/docks-deep-dive.html) is perfect for `symbols-view-plus`.

I'm planning to catch up with [the migration](https://github.com/atom/symbols-view/pull/203) of the official package `symbols-view` first. Any enhancement idea will be pended after that.

**Comment by aidistan** [comment]
@DamnedScholar Check the new theme "Dock Item" in v0.116.1-plus.1
